// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB7KNelxptrMZwjzUkTo197yQv07BTYy-g',
    appId: '1:738119635362:web:d3f8003cb289d70b4b22fb',
    messagingSenderId: '738119635362',
    projectId: 'iedc-rit-ideathon',
    authDomain: 'iedc-rit-ideathon.firebaseapp.com',
    storageBucket: 'iedc-rit-ideathon.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDXmxHU8y8g0gKTSCFH2vMKq1ntK2ThAl8',
    appId: '1:738119635362:android:a3f977549bb5d7f74b22fb',
    messagingSenderId: '738119635362',
    projectId: 'iedc-rit-ideathon',
    storageBucket: 'iedc-rit-ideathon.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBnpVZ-YsMZQ6dKs9WyGecVoMSE5s0Th6Y',
    appId: '1:738119635362:ios:306f190460ea000b4b22fb',
    messagingSenderId: '738119635362',
    projectId: 'iedc-rit-ideathon',
    storageBucket: 'iedc-rit-ideathon.firebasestorage.app',
    iosBundleId: 'com.example.ideathonWebsite',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBnpVZ-YsMZQ6dKs9WyGecVoMSE5s0Th6Y',
    appId: '1:738119635362:ios:306f190460ea000b4b22fb',
    messagingSenderId: '738119635362',
    projectId: 'iedc-rit-ideathon',
    storageBucket: 'iedc-rit-ideathon.firebasestorage.app',
    iosBundleId: 'com.example.ideathonWebsite',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB7KNelxptrMZwjzUkTo197yQv07BTYy-g',
    appId: '1:738119635362:web:01491bf7bb42ecd44b22fb',
    messagingSenderId: '738119635362',
    projectId: 'iedc-rit-ideathon',
    authDomain: 'iedc-rit-ideathon.firebaseapp.com',
    storageBucket: 'iedc-rit-ideathon.firebasestorage.app',
  );
}
